[package]
name = "smart-garden-gateway-mqtt-client"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/easybe/smart-garden-gateway-mqtt-client"
license = "GPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rumqttc = "0.22.0"
tokio = { version = "1.29.1", features = ["rt-multi-thread"] }
