[package]
name = "smart-garden-gateway-mqtt-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nng = "1.0.1"
rumqttc = "0.22.0"
tokio = { version = "1.29.1", features = ["rt-multi-thread"] }
